# Generated by Django 4.2.8 on 2023-12-07 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('schedule', '0002_schedule_end_time_schedule_name_schedule_start_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Price')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('equipmentType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.equipmenttype')),
                ('schedules', models.ManyToManyField(blank=True, to='schedule.schedule')),
            ],
        ),
    ]
