# Generated by Django 4.2.8 on 2023-12-08 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='frequency',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('monthly', 'Monthly')], max_length=50, null=True, verbose_name='Frequency'),
        ),
    ]
