# Generated by Django 4.2.8 on 2023-12-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_alter_equipmentactivitytrack_end_time_and_more'),
        ('package', '0002_package_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='equipmentType',
        ),
        migrations.AddField(
            model_name='package',
            name='equipmentType',
            field=models.ManyToManyField(blank=True, null=True, to='equipment.equipmenttype'),
        ),
    ]
