# Generated by Django 4.2.8 on 2023-12-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_alter_equipmentactivitytrack_end_time_and_more'),
        ('package', '0003_remove_package_equipmenttype_package_equipmenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='equipmentType',
            field=models.ManyToManyField(blank=True, to='equipment.equipmenttype'),
        ),
    ]
