# Generated by Django 4.2.8 on 2023-12-08 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='due_salary',
            field=models.FloatField(default=0, verbose_name='Due Salary'),
        ),
    ]
