# Generated by Django 4.2.8 on 2023-12-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0003_coach_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='nid',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NID'),
        ),
    ]
