# Generated by Django 4.2.8 on 2023-12-10 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_member_nid_member_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coach', '0004_coach_nid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachActivityTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField(blank=True, null=True, verbose_name='Booking start')),
                ('end_time', models.DateField(blank=True, null=True, verbose_name='Booking end')),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('booked_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.member')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coach.coach')),
            ],
        ),
    ]
