# Generated by Django 4.2.8 on 2023-12-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0006_rename_due_salary_coach_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
    ]
