# Generated by Django 4.2.8 on 2023-12-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0008_alter_coach_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachactivitytrack',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Booking end'),
        ),
        migrations.AlterField(
            model_name='coachactivitytrack',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Booking start'),
        ),
    ]
