# Generated by Django 4.2.8 on 2023-12-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='equipmentType',
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipmentType',
            field=models.ManyToManyField(blank=True, to='equipment.equipmenttype'),
        ),
    ]
