# Generated by Django 4.2.8 on 2023-12-10 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='serial',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Serial'),
        ),
    ]
