# Generated by Django 4.2.8 on 2023-12-10 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_member_nid_member_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0004_equipment_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentactivitytrack',
            name='booked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentactivitytrack',
            name='booked_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.member'),
        ),
        migrations.AlterField(
            model_name='equipmentactivitytrack',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment'),
        ),
    ]
