# Generated by Django 4.2.8 on 2023-12-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_equipment_brand_equipment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentactivitytrack',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Booking end'),
        ),
        migrations.AlterField(
            model_name='equipmentactivitytrack',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Booking start'),
        ),
    ]
