# Generated by Django 4.2.8 on 2023-12-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_alter_equipment_serial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentactivitytrack',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='equipmentactivitytrack',
            name='start_time',
        ),
        migrations.AddField(
            model_name='equipmentactivitytrack',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date(1 Hour)'),
        ),
    ]
