# Generated by Django 4.2.8 on 2023-12-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_remove_equipmentactivitytrack_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentactivitytrack',
            name='date',
        ),
        migrations.AddField(
            model_name='equipmentactivitytrack',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Booking end'),
        ),
        migrations.AddField(
            model_name='equipmentactivitytrack',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Booking start'),
        ),
    ]
