# Generated by Django 4.2.8 on 2023-12-07 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Full Name')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='Phone')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=50, null=True, verbose_name='Gender')),
                ('join_date', models.DateField(blank=True, null=True, verbose_name='Joining Date')),
                ('status', models.BooleanField(default=True, verbose_name='Active Status')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='package.package')),
            ],
        ),
    ]
