# Generated by Django 4.2.8 on 2023-12-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='memberId',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Member Id'),
        ),
    ]
