# Generated by Django 4.2.8 on 2023-12-08 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_member_memberid'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='due',
            field=models.FloatField(default=0, verbose_name='Due Payment'),
        ),
    ]
