# Generated by Django 4.2.8 on 2023-12-08 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_member_due'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='due',
            new_name='due_payment',
        ),
    ]
