# Generated by Django 4.2.8 on 2023-12-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_rename_due_member_due_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='nid',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NID'),
        ),
        migrations.AddField(
            model_name='member',
            name='ref',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Reference'),
        ),
    ]
