# Generated by Django 4.2.8 on 2023-12-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_member_nid_member_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Phone'),
        ),
    ]
