# Generated by Django 4.2.8 on 2023-12-07 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_member_memberid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='join_date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.member'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reason',
            field=models.CharField(blank=True, choices=[('package', 'Package'), ('private_session', 'Private Session')], max_length=50, null=True, verbose_name='Reason'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
