# Generated by Django 4.2.8 on 2023-12-08 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_remove_transaction_dob_remove_transaction_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transactionType',
            field=models.CharField(blank=True, choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=50, null=True, verbose_name='Transaction Type'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reason',
            field=models.CharField(blank=True, choices=[('package', 'Package'), ('private_session', 'Private Session'), ('salary_coach', 'Coach Salary'), ('salary_employee', 'Employee Salary')], max_length=50, null=True, verbose_name='Reason'),
        ),
    ]
