# Generated by Django 4.2.8 on 2023-12-10 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_alter_equipment_serial'),
        ('transaction', '0004_credit_debit_delete_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='credit',
            name='is_coach',
            field=models.BooleanField(default=False, verbose_name='Is Coach'),
        ),
        migrations.AddField(
            model_name='credit',
            name='is_equipment',
            field=models.BooleanField(default=False, verbose_name='Is Equipment'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='is_employee',
            field=models.BooleanField(default=False, verbose_name='Is Employee'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='reason',
            field=models.CharField(blank=True, choices=[('salary_coach', 'Coach Salary'), ('salary_employee', 'Employee Salary'), ('buy_equipment', 'Buy Equipment')], max_length=50, null=True, verbose_name='Reason'),
        ),
    ]
