# Generated by Django 4.2.8 on 2023-12-17 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_alter_member_ref'),
        ('transaction', '0005_credit_equipment_credit_is_coach_credit_is_equipment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March')], max_length=20, null=True, verbose_name='Month')),
                ('total_amount', models.FloatField(default=0, verbose_name='Total Amount')),
                ('payed_amount', models.FloatField(default=0, verbose_name='Payed Amount')),
                ('due_amount', models.FloatField(default=0, verbose_name='Due Amount')),
                ('advanced_amount', models.FloatField(default=0, verbose_name='Advanced Amount')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
        ),
    ]
