# Generated by Django 4.2.8 on 2023-12-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_alter_bill_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='reason',
            field=models.CharField(blank=True, choices=[('admission', 'Admission'), ('package_fee', 'Package Fee'), ('private_session', 'Private Session')], max_length=50, null=True, verbose_name='Reason'),
        ),
        migrations.AddField(
            model_name='bill',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='debit',
            name='reason',
            field=models.CharField(blank=True, choices=[('admission', 'Admission'), ('package_fee', 'Package Fee'), ('private_session', 'Private Session')], max_length=50, null=True, verbose_name='Reason'),
        ),
    ]
