# Generated by Django 5.1.5 on 2025-01-19 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_timetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='user',
        ),
    ]
