# Generated by Django 4.2.8 on 2023-12-07 10:44

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='Phone')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Full Name')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('is_manager', models.BooleanField(default=False, verbose_name='Manager')),
                ('is_staff', models.BooleanField(default=True, verbose_name='Staff')),
                ('salary', models.FloatField(blank=True, null=True, verbose_name='Salary')),
                ('district', models.CharField(blank=True, max_length=50, null=True, verbose_name='District')),
                ('ref', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reference')),
                ('institute', models.TextField(blank=True, null=True, verbose_name='Institute')),
                ('registrationId', models.CharField(blank=True, max_length=255, null=True, verbose_name='Registration Id')),
                ('is_payment_requested', models.BooleanField(default=False, verbose_name='Payment Request Status')),
                ('is_story_writing_participant', models.BooleanField(default=False, verbose_name='Story Writing Participation Status')),
                ('is_quiz_participant', models.BooleanField(default=False, verbose_name='Quiz Participation Status')),
                ('trxId', models.CharField(blank=True, max_length=255, null=True, verbose_name='Trx Id')),
                ('senderPhone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Sender Phone')),
                ('receiverPhone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Receiver Phone')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
