# Generated by Django 4.2.8 on 2023-12-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_schedule_end_time_schedule_name_schedule_start_time_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='district',
        ),
        migrations.RemoveField(
            model_name='user',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_payment_requested',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_quiz_participant',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_story_writing_participant',
        ),
        migrations.RemoveField(
            model_name='user',
            name='receiverPhone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ref',
        ),
        migrations.RemoveField(
            model_name='user',
            name='registrationId',
        ),
        migrations.RemoveField(
            model_name='user',
            name='senderPhone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='trxId',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=50, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_employee',
            field=models.BooleanField(default=True, verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='user',
            name='join_date',
            field=models.DateField(blank=True, null=True, verbose_name='Joining Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='schedules',
            field=models.ManyToManyField(blank=True, to='schedule.schedule'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Active Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
