# Generated by Django 4.2.8 on 2023-12-08 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_district_remove_user_institute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='due_payment',
            field=models.FloatField(default=0, verbose_name='Due Payment'),
        ),
    ]
