# Generated by Django 4.2.8 on 2023-12-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_nid'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastChecked', models.DateField(blank=True, null=True, verbose_name='Last Checked')),
            ],
        ),
    ]
