# Generated by Django 4.2.8 on 2023-12-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='due_payment',
        ),
        migrations.AddField(
            model_name='user',
            name='due',
            field=models.FloatField(default=0, verbose_name='Due Salary'),
        ),
    ]
