# Generated by Django 4.2.8 on 2023-12-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='Phone'),
        ),
    ]
