# Generated by Django 4.2.8 on 2023-12-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='join_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Joining Date'),
        ),
    ]
